---
# This role installs openam dist to the fr home directory. 
# Assumes the software has been downloaded and is available at {{ forgerock_download_dir }}/openam
# Pass in {{ tomcat_dir }} to this role. This should be the path the the openam tomcat instance

- name: unpack ssoadm tools
  command: creates={{ install_root }}/ssoadmin unzip {{ forgerock_download_dir }}/openam/SSOAdminTools-{{ openam_version }}.zip -d {{ install_root }}/ssoadmin
  
- name: unpack config tools
  command: creates={{ install_root }}/ssoconfigtool unzip {{ forgerock_download_dir }}/openam/SSOConfiguratorTools-{{ openam_version }}.zip -d {{ install_root }}/ssoconfigtool

- name: copy config file
  template: src=openam.config dest={{ install_root }}/ssoconfigtool/openam.config
 
- name: Ensure tomcat is running
  service: name="tomcat-openam" state=started pattern="tomcat-openam" enabled=yes

- name: Deploy war to tomcat
  command: creates={{ tomcat_dir }}/webapps/openam cp {{ forgerock_download_dir }}/openam/OpenAM-{{ openam_version }}.war {{ tomcat_dir }}/webapps/openam.war
 
- name: Wait for openam war to be fully deployed before running configurator
  wait_for: port=8080 delay=10
- uri: url=http://localhost:8080/openam status=302 timeout=120 async=120
  
- name: Run openam configurator
  command: creates={{install_root}}/openam java -jar {{ install_root }}/ssoconfigtool/openam-configurator-tool-{{ openam_version }}.jar -f {{ install_root }}/ssoconfigtool/openam.config
 
- name: copy policy.xml for import
  copy: src=policy.xml dest=etc/policy.xml  mode=0622

# This seems to be needed after a fresh install   
- name: restart Openam
  service: name="tomcat-openam" state=restarted enabled=yes

# 
- name: Wait for openam war to be fully deployed before running configurator
  wait_for: port=8080 delay=10
- uri: url=http://localhost:8080/openam status=302 timeout=120 async=120
  
  # Create ssoadm tools - set JAVA_HOME=/usr/lib/jvm/java
- name: setup ssoadm 
  command: chdir={{ install_root }}/ssoadmin {{ install_root }}/ssoadmin/setup -p {{ install_root }}/openam
  environment:
    JAVA_HOME: "{{java_home}}"
  
  

# This is failing on the when we are not using example.com domain- find out why later
# probably because root policy.xml needs to be fixed
#- name: Import policy.xml
#  command: bin/import-policies etc/policy.xml
