kind: PersistentVolume
apiVersion: v1
metadata:
  name: fstack
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    # This GCE PD must already exist.
    pdName: frstack
    fsType: ext4