---
# This role creates the demo forgerock user account that will be used for the remainder of the install

- name: Create fr demo user
  user: name=fr system=yes comment="ForgeRock Demo Account"

# Add your .ssh key under files and update this command to include it.
# This will allow you to ssh to the fr user account
- name: Append our .ssh key to the fr demo user 
  authorized_key: user=fr key="{{item}}"
  with_file:
    - warren_id_rsa.pub 

# Escaping is needed here to handle the colon in the NOPASSWD line
- name: Add fr user to sudoers
  action: 'lineinfile
          dest=/etc/sudoers
          regexp="\%^fr"
          line="fr ALL=NOPASSWD: ALL"'

# Some forgerock tools need JAVA_HOME set. TODO: Should we just template our .bash scripts?
- name: Set JAVA_HOME in our profile. 
  lineinfile: dest=/home/fr/.bash_profile regexp=^JAVA_HOME  line='export JAVA_HOME=${java_home}'