---
# This role creates the demo forgerock user account that will be used for the remainder of the install

- name: Create fr demo user
  user: name=fr system=yes comment="ForgeRock Demo Account"

# Add your .ssh key under files and update this command to include it.
# This will allow you to ssh to the fr user account
- name: Append our .ssh key to the fr demo user 
  authorized_key: user=fr key="{{item}}"
  with_file:
    - id_rsa.pub 

# Escaping is needed here to handle the colon in the NOPASSWD line
- name: Add fr user to sudoers
  action: 'lineinfile
          dest=/etc/sudoers
          regexp="\%^fr"
          line="fr ALL=NOPASSWD: ALL"'

# Some forgerock tools need JAVA_HOME set. TODO: Should we just template our .bash scripts?
- name: Set JAVA_HOME in our profile. 
  lineinfile: dest={{home_dir}}/.bashrc regexp=^JAVA_HOME  line='export JAVA_HOME={{java_home}}'
  
- name: create dirs
  file: path={{home_dir}}/{{item}} state=directory owner=fr
  with_items:
   - etc
   - bin
  
- name: create password file for ssoadm command
  template: src=amadmin_pw dest={{home_dir}}/etc/amadmin_pw mode=0400 owner=fr
  
- name: copy list-policies
  copy: src=list-policies dest={{home_dir}}/bin/list-policies mode=0755 owner=fr
   
- name: copy import-policies
  copy: src=import-policies dest={{home_dir}}/bin/import-policies mode=0755 owner=fr
  
