---
# Download nighlty build software locally to the ansible *host* (not the guest)
# Download to the  staging/ directory - which the guest can access as /vagrant/staging
# If the guest finds these cached files it can skip the download process
# This is not requried (the guest wil just downlod the s/w if it cant find it)- but it will speed up re-deploys 

# If you want updates nightlies you should delete files under staging/ so they get redownloaded again

- connection: local
  hosts: localhost
  sudo: no
  vars_files: 
    - vars/nightly.yml 
  tasks:
    - name: ensure staging dir exists
      file: path=staging state=directory 
# Note: get_url only skips the download if the destination is a file name - not a directory
# Because AM is so large, we explicty check for the filename so we dont redownload all the time
# If you want to update OpenAM, delete the file under staging/
    - get_url: url="{{openam_download_url }}" dest="staging/{{openam_zip_file}}"   
    - get_url: url="{{item}}" dest="staging/"
      with_items:
        - "{{ opendj_download_url }}" 
        - "{{ openidm_download_url }}"
        - "{{ openig_download_url }}" 
#        - "{{ tomcat_agent_download_url }}"
#        - "{{ apache_agent_download_url }}"