---

# Install the ForgeRock stack 
# Before this is run it is assumed some basic pre-reqs have been completed:
#
# - The software zip files must be available to the guest. They are
#  assumed to be in the ${download_dir}. The previous play should set this
#   up for the environment
# - Appropriate Firewall ports must be open on the guest. We use haproxy to put most things through 80/443
# - The "fr" ForgeRock user must be created with sudo priv. The vagrant.yml does this

# Tasks to complete with sudo privs
- remote_user: fr
  sudo: yes
  hosts: ois
  roles:
   - { role: common, tags: ["common"]}
   - { role: base-apache, tags: ["http"]}
   - { role: haproxy, tags: ["http"]}
   - { role: tomcat, tomcat_instance: 'tomcat-openam', tomcat_http_port: 8080,
        tomcat_https_port: 8443, tomcat_server_port: 8005, tags: ["tomcat"]}
   - { role: tomcat, tomcat_instance: 'tomcat-apps', tomcat_http_port: 18080,
        tomcat_https_port: 18443, tomcat_server_port: 18005, tags: ["tomcat"]}
   - { role: opendj, tags: ["opendj","ois"]}
   - { role: agent-apache, tags: ["agent"] }
   - { role: openidm, tags: ["openidm","ois"]}
 
# Plays to run as normal fr user    
- remote_user: fr
  hosts: ois
  roles: 
   - { role: openam, tomcat_dir: '/home/fr/tomcat-openam', tags: ["openam","ois"]}
   - { role: agent-tomcat, tags: ["agent"] }
   
 