---
# Set up Google Compute Engine node
# TODO: This needs to be retested
# Need commands to open firewall ports
#
# Download http://curl.haxx.se/docs/caextract.html  
# The first play needs to be run as your own userid here - since that is what 
# GCE creates the new instance account.
# This will create the demo fr user account that is used to complete the rest of the install
- name: Create a sandbox instance
  hosts: localhost
  connection: local
  vars:
    names: foo
    machine_type: f1-micro
    image: centos-6-v20131120
    zone: us-central1-a
  tasks:
    - name: Launch instances
      local_action: gce machine_type={{machine_type}} instance_names={{names}} image={{image}} zone={{zone}}
      register: gce
    - name: Add new instance to host group
      local_action: add_host hostname={{ item.public_ip }} groupname=launched
      with_items: gce.instance_data
    - name: Wait for SSH to come up
      local_action: wait_for host={{item.public_ip}} port=22 delay=10
                    timeout=60 state=started
      with_items: gce.instance_data


- name: add se-linux support
  hosts: launched
  sudo: True
  tasks:
    - name: install  libselinux-python package on target
      yum: name="libselinux-python" state=latest
 
- name: Configure instance(s)
  hosts: launched
  sudo: True
  roles:
    - create-fr-user