---

# Download local s/w to shared folder
# Download software locally to the ansible *host* (not the guest)

- hosts: 127.0.0.1
  connection: local
  
  vars:
#    openam_version: "12.0.0-SNAPSHOT"
#    openam_download_url: "http://download.forgerock.org/downloads/openam/OpenAM-{{ openam_version }}_nightly_20140731.zip"
    proxy_env:
        http_proxy: http://localhost:2001
        https_proxy: http://localhost:2001
  vars_files:
      - vars/nightly.yml
  tasks: 
    - name: download software
      get_url: url={{item }} dest=staging/
      environment: proxy_env
      with_items:   
        - "{{ openam_download_url }}"
#        - "{{ opendj_download_url }}"
#        - "{{ tomcat_agent_download_url }}"
#        - "{{ apache_agent_download_url }}"
#        - "{{ openidm_download_url }}"
#        - "{{ haproxy_download_url  }}"
#        - "{{ openjdk_download_url }}"
#        - "{{ openig_download_url }}" 
#        - "{{ tomcat_download_url }}"
    
    - name: unpack openam for later install
      local_action: command creates=tmp/openam unzip tmp/{{openam_zip}} -d tmp/openam