---
# Installs the Apache OpenAM agent
# Needs to be run as root - as the Apache httpd conf dir is owned by non fr user

  
- name: Unpack archive
  unarchive: src="{{staging_dir}}/apache_v24_agent.zip" dest="{{install_root}}" copy=no
    
- name: create password file
  copy: src=agentpw dest="{{ webagents_home }}/agentpw"

  
- name: Stop apache
  service: name=httpd state=stopped
  
- name: Copy agent response template 
  template: src=agentresponse-custom.txt dest="{{ webagents_home }}/agentresponse-custom.txt" 

- name: Run agentadmin 
  shell: "{{ webagents_home }}/apache24_agent/bin/agentadmin --acceptLicense --custom-install --useResponse {{ webagents_home }}/agentresponse-custom.txt"
  
- name: Change ownership of agent files 
  file: path="{{ webagents_home }}" owner=fr group=apache recurse=yes state=directory
  
- name: start apache
  service: name=httpd state=started
  