---
# This role installs openam in tomcat
# This assumes tomcat has already been installed
# Assumes the software has been downloaded and is available at {{ forgerock_download_dir }}/openam
# Uses the variable {{ tomcat_openam_dir }} to know where to install the war file. 
#  This should be the path to the openam tomcat instance dir

- pip: name=requests
- include: ../../openam-uninstall.yml

# download openam or used cached copy
- include: ../../download.yml download_file="{{openam_zip_file}}" download_url="{{openam_download_url}}"
  
- name: Unpack downloaded OpenAM bits
  command: chdir="{{download_dir}}" unzip "{{openam_zip_file}}"

# create install dir, openam dir
- file: path="{{ install_root}}" owner="{{ fr_user }}" state="directory" 

# Note that the openam config dir has to be writable by the user who runs the web container
# In our case that is tomcat. TODO: Use group permissions here
- file: path={{ install_root}}/openam owner={{fr_user}} state="directory" 

#- name: unpack config tools
#  command: creates="{{ install_root }}/ssoconfigtool" unzip {{ download_dir }}/openam/SSOConfiguratorTools-{{ openam_version }}.zip -d {{ install_root }}/ssoconfigtool
  
#- name: copy config file from template
#  template: src=openam.config dest="{{ install_root }}/ssoconfigtool/openam.config" owner="{{fr_user}}" mode=0644

- name: Deploy war to tomcat
  command: creates="{{ tomcat_openam_dir }}/webapps/openam" cp "{{ download_dir }}/openam/OpenAM-{{ openam_version }}.war" "{{ tomcat_openam_dir}}/webapps/openam.war"

- name: Ensure openam tomcat instance is running
  service: name="openam.service" state=restarted enabled=yes

- name: Wait for openam war to be fully deployed before running configurator
  wait_for: port={{openam_server_port}} delay=10

# Bit of hack. The previous command waits for the port -but AM could still be deploying
# So this waits another 30 seconds to be safe
- wait_for: port={{openam_server_port}} delay=30

- name: Run ssoconfigure
  ssoconfigure: server_url="http://openam.example.com:8080"
    deployment_uri="/openam"
    base_dir="{{install_root}}/openam"
    directory_server="{{opendj_host}}"
    root_suffix="o=openam"
    directory_admin_port="1{{opendj_admin_port}}"
    directory_jmx_port="1{{opendj_jmx_port}}"
    directory_port="1{{opendj_ldap_port}}"
    ds_dirmgrdn="{{opendj_dirmgr}}"
    data_store="embedded"
    ds_dirmgrpasswd="{{opendj_password}}"
    amldapuserpasswd="{{amldapuser_password}}"
    cookie_domain="{{openam_cookie_domain}}"
    admin_pwd="{{amadmin_password}}"
    acceptlicense="true"
    am_enc_key="AQICY6Za5J5noktyqnhW10JiPVNUdKuiZYwS"
    lb_site_name="sitea"
    lb_primary_url="{{openam_site_url}}"
    
#  - name: Run openam configurator
#  command: creates={{install_root}}/openam/bootstrap java -jar {{ install_root }}/ssoconfigtool/openam-configurator-tool-{{ openam_version }}.jar 
#         --file {{ install_root }}/ssoconfigtool/openam.config --acceptLicense
         
#- name: Run openam configurator
#  command: creates="{{install_root}}/openam/bootstrap" java -jar "{{ install_root }}/ssoconfigtool/openam-configurator-tool-{{ openam_version }}.jar"
#         --file "{{ install_root }}/ssoconfigtool/openam.config" "{{ openam_license_switch }}"

# Make sure everything is owned by fr user  
- file: recurse=yes state=directory  owner="{{ fr_user }}" 
     group="tomcat" path="{{ install_root}}" mode=0775
