apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: openam-b
  name: openam-b
spec:
  replicas: 1
  selector:
    name: openam-b
  template:
    metadata:
      labels:
         name: openam-b
         site: site1
    spec:
      containers:
      - name: openam-b
        image: wstrange/openam-nightly
        ports:
        - name: openam
          containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: openam-disk-b
          mountPath: /root/openam
      volumes:
      - name: openam-disk-b
        gcePersistentDisk:
          pdName: openam-disk-b
          fsType: ext4
