# Creates a persistent volume using an NFS share
# The share comes from a GCE support instance that is running
# This is our "persistence" service


kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv01
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /opt/share
    server: 10.240.73.181


---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv01claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi