---
# Install Kubernetes on a Centos / Fedora machine, all on a single node
# This is for testing /dev

#- name: Install required packages
#  yum: name={{item}} state=latest
#  with_items:
#   - docker
#   - etcd
#   - golang
#
#
- get_url:  url=https://github.com/kubernetes/kubernetes/archive/v1.0.6.tar.gz dest=/tmp/k8_src.tar.gz
- file: name=/opt state=directory
- unarchive: src=/tmp/k8_src.tar.gz dest=/opt copy=no

