---
# Install Kubernetes on a Centos / Fedora machine, all on a single node
# This is for testing /dev

#- name: Install required packages
#  yum: name={{item}} state=latest
#  with_items:
#   - docker
#   - etcd
#   - golang
#
#
#- get_url: url=https://github.com/kubernetes/kubernetes/releases/download/v1.0.5/kubernetes.tar.gz dest=/tmp
- get_url:  url=https://github.com/kubernetes/kubernetes/archive/v1.0.5.tar.gz dest=/tmp/k8_src.tar.gz
#- unarchive: src=/tmp/kubernetes.tar.gz dest=/opt copy=no
- unarchive: src=/tmp/k8_src.tar.gz dest=/opt copy=no

