apiVersion: v1beta3
kind: Service
metadata:
  name: openam-a
  label:
    - name: openam-a
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: "TCP"
  publicIPs:
    - 172.17.8.102
  selector:
    name: openam-a
