# Run OpenIDM on k8
apiVersion: v1
kind: Pod
metadata:
  name: openidm
  labels:
    name: openidm
spec:
  containers:
  - name: openidm
    image: wstrange/openidm-nightly
    ports:
    - containerPort: 8080

---
# Service definition
apiVersion: v1
kind: Service
spec:
  selector:
    name: openidm
  ports:
  - port: 8080
    targetPort: 8080
  type: NodePort
  - nodePort: 9090
