---
# This role installs opendj in /opt

# Moved from using rpm to unzip - since it works across both Debian / Centos
#- name: install opendj rpm
#  yum: name={{ download_dir }}/{{ opendj_rpm }} state=installed
  
- name: unpack opendj
  command: chdir=/opt creates=/opt/opendj unzip {{ forgerock_download_dir }}/{{ opendj_zip }}

- name: copy opendj props file
  template: src=opendj.properties dest=/tmp/opendj.properties 
  
- name: setup opendj
  command: creates=/opt/opendj/config /opt/opendj/setup --cli --propertiesFilePath /tmp/opendj.properties --acceptLicense --no-prompt 

- name: Create rc script
  command: /opt/opendj/bin/create-rc-script -f /etc/init.d/opendj -u root
  
- name: Change the ownership on the files so the fr user can execute ldap commands
  file: path=/opt/opendj state=directory owner=fr recurse=yes

- name: Start opendj
  service: name=opendj state=restarted enabled=yes
  
- name: Create suffix for openam config store
  command: /opt/opendj/bin/dsconfig set-backend-prop --backend-name userRoot --add base-dn:dc=openam,dc=forgerock,dc=org
    --hostname localhost --port 4444 --bindDN cn=Directory\ Manager --bindPassword password
    --trustAll --noPropertiesFile --no-prompt
    