---
# This role installs openidm

  
- name: unpack openidm
  command: creates={{install_root}}/openidm unzip {{download_dir}}/{{openidm_zip}} -d {{install_root}}

- name: copy jetty.xml to use custom ports
  template: src=jetty.xml dest={{install_root}}/openidm/conf
  
- name: copy conf files
  copy: src=conf dest={{install_root}}/openidm mode=0644
  
- name: copy script files
  copy: src=script dest={{install_root}}/openidm mode=0644
  
- name: copy workflows 
  copy: src=workflow dest={{install_root}}/openidm mode=0644

- name: copy sample xml data 
  copy: src=data dest={{install_root}}/openidm mode=0644
  
- name: create service start up script
  template: src=openidm dest=/etc/init.d/openidm  mode=0755
  
- name: Change ownership of openidm to fr user
  file: path={{install_root}}/openidm owner={{fr_user}} state=directory recurse=yes
  
- name: Enable openidm service
  service: name=openidm state=restarted enabled=yes