---
# This role installs common base pre-reqs for the ForgeRock stack

- name: Install required packages
  yum: name={{item}} state=latest
  with_items:
   - unzip
   - git
   - wget
#   - java-1.7.0-openjdk-devel
#Use the above if you have lots of bandwidth.
# Below uses a pre-downloaded JDK - which saves download bandwidth if you are doing repeated installs or testing
- name: Check for pre downloaded JDK
  stat: path={{download_dir}}/{{jdk_rpm}}
  register: jdkarchive
  
- name: Install java from pre-downloaded jdk
  yum: name={{download_dir}}/{{jdk_rpm}} state=present
  when: jdkarchive.stat.exists
  
- name: No pre-loaded JDK - Install JDK from yum
  yum: name="java-1.7.0-openjdk-devel" state=present
  when: jdkarchive.stat.exists == false
  
- name: Put our fqdn in /etc/hosts
  lineinfile: dest=/etc/hosts line="127.0.0.1 {{openam_fqdn}} {{openam_hostname}}" regexp="{{openam_fqdn}}"  state=present
  
- name: create top level software dir
  file: state=directory path={{install_root}} owner=fr mode=0755