---
# Download S/W to the *hosts* staging dir
# DEPRECATED- NO LONGER USED
# This can be used to 
# Run this with ansible-playbook -i ../etc/hosts download_sw.yml

- hosts: 127.0.0.1
  connection: local
  vars_files:
    - "vars/{{release}}.yml"
  tasks:
    - get_url: url="{{openam_download_url}}"  dest="../staging/{{openam_zip}}"
    - get_url: url="{{openidm_download_url}}"  dest="../staging/{{openidm_zip}}"   
    - get_url: url="{{openig_download_url}}"  dest="../staging/{{openig_zip}}"
    - get_url: url="{{opendj_download_url}}"  dest="../staging/{{opendj_zip}}"
    - get_url: url="{{tomcat_agent_download_url}}"  dest="../staging/{{tomcat_agent_zip}}"
    - get_url: url="{{apache_agent_download_url}}"  dest="../staging/{{apache_agent_zip}}"