apiVersion: v1beta3
kind: Pod
metadata:
  labels:
    name: haproxy
  name: haproxy
spec:
    containers:
    - name: haproxy
      image: wstrange/frstack-haproxy
      ports:
      - name: http
        containerPort: 80