#
# This pod imports nfs-server.default.kube.local:/ into /usr/share/nginx/html
#

apiVersion: v1
kind: Service
metadata:
  name: ldap
spec:
  ports:
    - port: 1389
      targetPort: 1389
      protocol: "TCP"
      name: ldap

---
apiVersion: v1
kind: Endpoints
metadata:
  name: ldap
subsets:
  addresses:
    - IP: 1.2.3.4
  ports:
    - port: 1389
    