#
# This pod imports nfs-server.default.kube.local:/ into /usr/share/nginx/html
#

apiVersion: v1
kind: Pod
metadata:
  name: nfs-web
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
      volumeMounts:
          # name must match the volume name below
          - name: nfs
            mountPath: "/usr/share/nginx/html"
  volumes:
    - name: nfs
      persistentVolumeClaim:
        claimName: pv01claim
#    - name: nfs
#      nfs:
#        # Used the internal IP of the GCE support NFS server. Works now
#        server: 10.240.73.181
#        path: "/opt/share"


 # Test...
 #mount -v -t nfs4 10.240.73.181:/opt/share /mnt
