---
# Installs the Apache OpenAM agent
# Needs to be run as root - as the Apache httpd conf dir is owned by non fr user

- name: Install OpenAM Apache Agent
  command: chdir=/home/fr creates={{ webagents_home }}/apache22_agent /usr/bin/unzip {{ download_dir }}/{{ apache_agent_version }}.zip
  
- name: create password file
  copy: src=agentpw dest={{ webagents_home }}
  
- name: Copy license agreement so we don't get prompted
  copy: src=license.log dest={{ webagents_home }}/apache22_agent/data
  
- name: Change ownership of agent files 
  file: path={{ webagents_home }} owner=fr group=apache recurse=yes state=directory
 
- name: Stop apache
  service: name=httpd state=stopped
  
- name: Copy agent response template 
  template: src=agentresponse-custom.txt dest={{ webagents_home }}/apache22_agent 

- name: Run agentadmin 
  command: "{{ webagents_home }}/apache22_agent/bin/agentadmin --custom-install --useResponse {{ webagents_home }}/apache22_agent/agentresponse-custom.txt"
  
- name: start apache
  service: name=httpd state=started
  
  