apiVersion: v1beta3
kind: ReplicationController
metadata:
  labels:
    name: haproxy
  name: haproxy
spec:
  replicas: 1
  selector:
    name: haproxy
  template:
    metadata:
      labels:
         name: haproxy
    spec:
      containers:
      - name: haproxy
        image: wstrange/haproxy-test
        ports:
        - name: http
          containerPort: 80