apiVersion: v1beta3
kind: Service
metadata:
  name: opendj
  label:
    - name: opendj
spec:
  ports:
    - port: 389
      targetPort: 389
      protocol: "TCP"
      name: opendj-389
  createExternalLoadBalancer: true
  selector:
    name: opendj
