---
# Configure OpenAM on base image
# This assumes openam is running

- hosts: localhost
  connection: local
  tasks:
  - name: Configure Primary OpenAM instance
    ssoconfigure: server_url="{{item}}"
      deployment_uri="/openam"
      base_dir="/root/openam"
      directory_server="opendj"
      root_suffix="dc=example,dc=com"
      directory_admin_port="4444"
      directory_jmx_port="1689"
      directory_port="389"
      ds_dirmgrdn="cn=Directory Manager"
      data_store="dirServer"
      ds_dirmgrpasswd="password"
      amldapuserpasswd="Passw0rd"
      userstore_type="LDAPv3ForOpenDS"
      userstore_ssl="SIMPLE"
      userstore_host="opendj"
      userstore_port="389"
      userstore_mgrdn="cn=Directory Manager"
      userstore_passwd="password"
      userstore_suffix="dc=example,dc=com"
      cookie_domain=".example.com"
      admin_pwd="password"
      acceptlicense="true"
      am_enc_key="AQICY6Za5J5noktyqnhW10JiPVNUdKuiZYwS"
      lb_site_name="site1"
      lb_primary_url="http://openam.example.com:80/openam"
      lb_session_ha_sfo="true"
    with_items:
      - http://openam-a.example.com:80/
      - http://openam-b.example.com:80/