apiVersion: v1beta3
kind: Service
metadata:
  name: openam-svc-b
  label:
    name: openam-svc-b
spec:
  ports:
    - port: 80
      targetPort: openam
      protocol: "TCP"
      name: openam-b
  selector:
    name: openam-b
  createExternalLoadBalancer: true
