apiVersion: v1beta3
kind: ReplicationController
metadata:
  labels:
    name: opendj
  name: opendj
spec:
  replicas: 1
  selector:
    name: opendj
  template:
    metadata:
      labels:
         name: opendj
    spec:
      containers:
      - name: opendj
        image: wstrange/opendj-nightly
        ports:
        - name: opendj-389
          containerPort: 389
          protocol: TCP