apiVersion: v1beta3
kind: Service
metadata:
  name: openam-a
  label:
    - name: openam-a
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: "TCP"
      name: openam-80
    - port: 389
      targetPort: 389
      protocol: "TCP"
      name: opendj-389
  createExternalLoadBalancer: true
  selector:
    name: openam-a
